browser:
  _target_: selenium.webdriver.Chrome
  service:
    _target_: selenium.webdriver.chrome.service.Service
    executable_path: "/usr/bin/chromedriver"
  options:
    _target_: webdriver.core.options.ChromeOptionsBuilder
    binary_location: "/usr/bin/chromium"
    headless: false
    arguments:
      - "--no-sandbox"
      - "--disable-dev-shm-usage" 
      - "--disable-gpu"
      - "--disable-extensions"
# see chrome options for arguments
    preferences:
      disable_images: false
      disable_javascript: false
    user_agent: null

timeouts:
  implicit: 10
  page_load: 30
  element_wait: 15
