# conf/test_config 
#
# config to run tests on the webdriver. 
#
defaults:
  - webdriver: test_webdriver
  - proxy: test_proxy
  - _self_

# Global package settings
package:
  name: "webdriver_proxy"
  version: "0.1.0"
