defaults:
  - webdriver: chrome
  - proxy: disabled
  - _self_

# Global package settings
package:
  name: "webdriver_proxy"
  version: "0.1.0"

# Test 
test:
  name: "This is a test load config"
  number: 42

